# Generated by Django 4.1.7 on 2023-04-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='clients',
        ),
    ]
