# Generated by Django 4.1.7 on 2023-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_alter_clients_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_date', models.DateField()),
                ('hours', models.IntegerField()),
                ('task_type', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_hour', models.IntegerField()),
                ('claimed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BankContacts',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='PaymentRecords',
        ),
        migrations.DeleteModel(
            name='TaskRecords',
        ),
    ]
